server:
  port: 4000
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
        server-addr: 127.0.0.1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      seata: true
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/x_order
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123
mybatis:
  config-location: classpath:mybatis-config.xml

seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: projectA # Seata 事务组编号，用于 TC 集群名
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      projectA: default
  # Seata 注册中心配置项，对应 RegistryProperties 类
  registry:
    type: nacos # 注册中心类型，默认为 file
    nacos:
      cluster: default # 使用的 Seata 分组
      namespace: # Nacos 命名空间
      serverAddr: localhost:8848 # Nacos 服务地址